# Generated by Django 2.2.4 on 2020-02-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_profile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='shuklanushiv@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='qwerty@123', max_length=300),
        ),
    ]
